### PR TITLE
Fix screenshot dates

### LINKED ISSUE #21: screenshot date is wrong
I took a screenshot for the README on 2017-08-26, but it says 2017-07-06...

screenshot.

### PR DESCRIPTION
**Pull request by WasabiFan**
There were a couple problems here.

Fixes #21

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -7,7 +7,8 @@ export function sanitizedDateString(date?: Date) {
     const d = date || new Date();
     const pad = (num: number) => ("00" + num).slice(-2);
 
-    return `${d.getFullYear()}-${pad(d.getMonth())}-${pad(d.getDay())}-${pad(d.getHours())}-${pad(d.getMinutes())}-${pad(d.getSeconds())}`;
+    // Months are zero-indexed
```
Comment (dlech) [inline src/utils.ts]: That's weird.

**Comment by dlech** [comment]
Thanks!
